name: tinder_clone
description: Tinder Clone
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  get: ^4.6.6
  dio: ^5.3.3
  image_picker: ^1.0.4
  provider: ^6.0.5
  preload_page_view: ^0.2.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  country_picker: ^2.0.21
  flutter_native_splash: ^2.3.4
  otp_text_field: ^1.1.3
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
